import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import Carouseler from '../components/Carouseler'
import Carousel from '../components/Carousel'
import AboutComp from '../components/AboutComp'
import ServicesComp from '../components/Services'
import Retailer from '../components/Retailer'
import ContactComp from '../components/ContactComp'
import Footer from '../components/Footer'
import Navigator from '../components/Navigator'
import { useRef } from 'react'

export default function Home() {
  let navRef = useRef();
  return (
    <div className="h-full w-full flex flex-col ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content='width=device-width,initial-scale=0.7'/>
      </Head>
      <div className='bg-center bg-no-repeat md:bg-[url("/images/banner-bg.png")] w-full h-[100vh]  border-[3px] border-green-600' style={{backgroundSize:"100%",backgroundPosition:"0% 0%"}}
      >
  
   <Nav></Nav>
  
   <Carouseler
   tailwind = "w-[75%] h-[80vh] ml-auto mr-auto overflow-hidden mt-[10%] transition-[ease all 0.5s]"
   children= {[<Carousel />,<Carousel />]}
   controls = {[<div className='w-10 h-10 bg-[url("/images/left-icon.png")] bg-pink-600 bg-no-repeat bg-center rounded-full'></div>,<div className='w-10 h-10 bg-[url("/images/right-icon.png")] bg-black bg-no-repeat bg-center rounded-full'></div>]}
   ></Carouseler>
      </div>
      <AboutComp></AboutComp>
      <ServicesComp></ServicesComp>
<Retailer></Retailer>
{/* <div className='w-full h-[80vh]' style={{backgroundImage:"url('/images/newsletter-bg.png')"}}>
  <div className='bg-pink-600 border-[10px] w-[100%] md:w-[70%] rounded-sm h-[60%] pt-[90px] md:rounded-[100%] border-red-200 md:h-[65%] ml-auto mr-auto mt-20 pl-[2%] pr-[2%] md:pt-[10%] pb[10%] lg:w-[35%] flex flex-col'>
<div className='w-fit ml-auto mr-auto text-2xl md:text-3xl text-white'>Subscribe to our newsletter</div>
<input className='focus:outline-none w-[60%] pl-2  rounded-md ml-auto mr-auto mt-[5%]  h-[10%]'></input>
<button className='w-fit pl-2 pr-2 pt-1 pb-1 bg-black shadow-lg focus:shadow-none hover:bg-slate-800 text-white rounded-md content-center ml-auto mr-auto mt-[2%]'>Subscribe</button>
  </div>
</div> */}
<div className='w-[100%] sm:w-[70%] md:w-[50%] h-[40vh] shadow-xl bg-pink-600  rounded-xl  mt-10 mb-10 ml-auto mr-auto flex flex-col pt-[5%]'>
<div className='w-fit ml-auto mr-auto text-2xl md:text-3xl text-white'>Subscribe to our newsletter</div>
<input className='focus:outline-none w-[90%] sm:w-[70%] md:w-[60%] pl-2 mb-[4%] rounded-md ml-auto mr-auto mt-[5%]  h-[20%]'></input>
<button className='w-fit pl-4  pr-4 pt-2 pb-2 bg-black shadow-lg focus:shadow-none hover:bg-slate-800 text-white rounded-md content-center ml-auto mr-auto mt-[2%]'>Subscribe</button>
</div>
<ContactComp></ContactComp>
<Footer></Footer>
    </div>
  )
}
